# Generated by Django 3.2.7 on 2021-11-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('slug', models.SlugField(default='', max_length=255, unique=True)),
                ('username', models.CharField(default='', max_length=30, unique=True, verbose_name='Логин')),
                ('avatar', models.ImageField(blank=True, default='settings.STATIC_ROOT/images/icons/default-avatar.png', upload_to='accounts/users/avatars', verbose_name='Аватар')),
                ('password', models.CharField(default='', max_length=30, verbose_name='Пароль')),
                ('email', models.EmailField(default='', max_length=30, verbose_name='Email')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Сотрудник')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Администратор')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время регистрации')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
