# Generated by Django 3.2.7 on 2021-11-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default='', max_length=30, unique=True, verbose_name='Username')),
                ('avatar', models.ImageField(blank=True, default='settings.STATIC_ROOT/images/icons/default-avatar.png', upload_to='accounts/users/avatars', verbose_name='Avatar')),
                ('password', models.CharField(default='', max_length=30, verbose_name='Password')),
                ('email', models.EmailField(default='', max_length=30, verbose_name='Email')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registratid date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
