# Generated by Django 3.2.7 on 2022-01-15 20:17

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0003_alter_video_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='author',
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(default='', upload_to='electrical/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.ImageField(blank=True, default='', upload_to='electrical/images/previews', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
    ]
