# Generated by Django 3.2.7 on 2022-01-16 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0005_alter_video_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(default='', upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.ImageField(default='', upload_to='images/previews', verbose_name='Превью'),
        ),
    ]
