# Generated by Django 3.2.7 on 2022-01-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0006_auto_20220116_1230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Movie',
        ),
    ]
