# Generated by Django 3.2.7 on 2022-01-17 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0007_rename_video_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
