# Generated by Django 4.0.4 on 2022-07-15 16:18

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('electrical', '0008_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('pdf', models.FileField(default='', upload_to='catalogs/')),
                ('preview', models.ImageField(blank=True, default='', upload_to='catalog_previews/')),
            ],
        ),
        migrations.CreateModel(
            name='Modal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('image', models.ImageField(blank=True, default='', upload_to='products/')),
                ('software_link', models.CharField(blank=True, default='', max_length=255)),
                ('catalogs', models.ManyToManyField(to='electrical.catalog')),
                ('modals', models.ManyToManyField(to='electrical.modal')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.FileField(default='', upload_to='timetables/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_on_map', models.CharField(default='', max_length=255)),
                ('states', models.ManyToManyField(to='electrical.state')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('youtube_link', models.CharField(default='', max_length=255)),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='electrical.product')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255, unique=True)),
                ('email', models.EmailField(default='', max_length=255, unique=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, unique=True)),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('extended_number', models.CharField(blank=True, default='', max_length=255)),
                ('position', models.CharField(default='', max_length=255)),
                ('organization', models.CharField(default='', max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('region', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='electrical.region')),
            ],
        ),
    ]
