# Generated by Django 4.0.4 on 2022-07-15 16:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modal',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
    ]
