# Generated by Django 4.0.4 on 2022-07-15 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0010_alter_modal_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='pdf',
            field=models.FileField(default='', upload_to='catalogs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='preview',
            field=models.ImageField(blank=True, default='', upload_to='catalog_previews/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='products/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='table',
            field=models.FileField(default='', upload_to='timetables/', validators=[django.core.validators.FileExtensionValidator(['ods', 'xls', 'xlsx'])]),
        ),
    ]
