# Generated by Django 4.0.4 on 2022-07-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0013_alter_product_modals'),
    ]

    operations = [
        migrations.AddField(
            model_name='modal',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
