# Generated by Django 4.0.4 on 2022-07-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0014_modal_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
