# Generated by Django 4.0.4 on 2022-07-15 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0015_region_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='states',
        ),
        migrations.AddField(
            model_name='state',
            name='region',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='electrical.region'),
        ),
    ]
