# Generated by Django 4.0.4 on 2022-07-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0016_remove_region_states_state_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='software_link',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='youtube_link',
            field=models.URLField(default='', max_length=255),
        ),
    ]
