# Generated by Django 4.0.4 on 2022-07-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0017_alter_product_software_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvideo',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='videos',
            field=models.ManyToManyField(blank=True, to='electrical.productvideo'),
        ),
    ]
