# Generated by Django 4.0.4 on 2022-07-15 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0018_remove_productvideo_product_product_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvideo',
            name='preview',
            field=models.ImageField(blank=True, default='', upload_to='catalog_previews/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
