# Generated by Django 3.2.7 on 2022-07-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0019_productvideo_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
