# Generated by Django 3.2.7 on 2022-07-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0020_product_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
