# Generated by Django 3.2.7 on 2022-07-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0021_alter_product_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catalogs',
            field=models.ManyToManyField(blank=True, to='electrical.Catalog'),
        ),
    ]
