# Generated by Django 3.2.7 on 2022-07-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0023_contactperson_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='priority',
            new_name='order',
        ),
    ]
