# Generated by Django 3.2.7 on 2022-07-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0027_region_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='slug',
        ),
    ]
