# Generated by Django 3.2.7 on 2022-07-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0028_remove_region_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='slug',
            field=models.SlugField(default='', max_length=255),
        ),
    ]
