# Generated by Django 3.2.7 on 2022-07-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0029_catalog_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='color_on_map',
            new_name='color',
        ),
        migrations.AddField(
            model_name='region',
            name='hover_color',
            field=models.CharField(default='', max_length=255),
        ),
    ]
