# Generated by Django 3.2.7 on 2022-07-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0030_auto_20220717_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='slug',
            field=models.SlugField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
    ]
