# Generated by Django 3.2.7 on 2022-07-17 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0031_auto_20220717_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='region',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='electrical.region'),
        ),
    ]
