# Generated by Django 3.2.7 on 2022-07-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0033_alter_state_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='hover_color',
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
