# Generated by Django 3.2.7 on 2022-07-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0034_auto_20220717_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='hover_color',
            field=models.CharField(default='', max_length=255),
        ),
    ]
