# Generated by Django 3.2.7 on 2022-07-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0035_region_hover_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='slug',
            field=models.SlugField(default='', max_length=255),
        ),
    ]
