# Generated by Django 3.2.7 on 2022-07-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0036_region_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='color',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='hover_color',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
    ]
