# Generated by Django 4.0.4 on 2022-07-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0037_auto_20220717_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='modal',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
    ]
