# Generated by Django 4.0.4 on 2022-07-20 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0038_modal_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description1',
        ),
    ]
