# Generated by Django 4.0.4 on 2022-07-20 05:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0039_rename_description_product_description1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
    ]
