# Generated by Django 4.0.4 on 2022-07-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0040_product_description2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
