# Generated by Django 4.0.4 on 2022-07-20 17:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0041_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description3',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
    ]
