# Generated by Django 4.0.4 on 2022-07-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0042_product_description3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modal',
            old_name='title',
            new_name='button_title',
        ),
        migrations.AddField(
            model_name='modal',
            name='button_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
