CATALOGS = { 
    "clamp-connections":{
        "category":"clamp-connections",
        "link":"/electrical/catalog/clamp-connections",
        "filename":"clamp-connections.pdf",
        "title":"Клеммные соединения Entrelec",
        "preview":"/static/main/catalog_files/images/clamp-connections/clamp-connections.png",
        "target":"_blank",
    },
    "clamps-with-varistors-and-protective-diods":{
        "category":"clamp-connections",
        "link":"/electrical/catalog/clamps-with-varistors-and-protective-diods",
        "filename":"clamps-with-varistors-and-protective-diods.pdf",
        "title":"Клеммы с варисторами и защитными диодами",
        "preview":"/static/main/catalog_files/images/clamp-connections/clamps-with-varistors-and-protective-diods.png",
        "target":"_blank",
    },
    "relays":{
        "category":"relays",
        "link":"/electrical/catalog/relays",
        "filename":"relays.pdf",
        "title":"Промышленные реле",
        "preview":"/static/main/catalog_files/images/relays/relays.png",
        "target":"_blank",
    }, 
    "spiral-ribbon":{
        "category":"spiral-ribbon",
        "link":"/electrical/catalog/spiral-ribbon",
        "filename":"spiral-ribbon.pdf",
        "title":"Спиральная лента",
        "preview":"/static/main/catalog_files/images/spiral-ribbon/spiral-ribbon.png",
        "target":"_blank",
    }, 
    "distribution-blocks":{
        "category":"distribution-blocks",
        "link":"/electrical/catalog/distribution-blocks",
        "filename":"distribution-blocks.pdf",
        "title":"Распределительные блоки серии DBL",
        "preview":"/static/main/catalog_files/images/distribution-blocks/distribution-blocks.png",
        "target":"_blank",
    }, 
}