CATALOGS = { 
    "clamp-connections":{
        "category":"clamp-connections",
        "link":"/electrical/catalog/clamp-connections",
        "filename":"clamp-connections.pdf",
        "title":"Клеммные соединения Entrelec",
        "preview":"/static/main/catalog_files/images/clamp-connections/clamp-connections.png",
        "target":"_blank",
    },
    "clamps-with-varistors-and-protective-diods":{
        "category":"clamp-connections",
        "link":"/electrical/catalog/clamps-with-varistors-and-protective-diods",
        "filename":"clamps-with-varistors-and-protective-diods.pdf",
        "title":"Клеммы с варисторами и защитными диодами",
        "preview":"/static/main/catalog_files/images/clamp-connections/clamps-with-varistors-and-protective-diods.png",
        "target":"_blank",
    },
    "relays":{
        "category":"relays",
        "link":"/electrical/catalog/relays",
        "filename":"relays.pdf",
        "title":"Промышленные реле",
        "preview":"/static/main/catalog_files/images/relays/relays.png",
        "target":"_blank",
    }, 
    "force-guided":{
        "category":"relays",
        "link":"/electrical/catalog/force-guided",
        "filename":"force-guided.pdf",
        "title":"Schrack force guided relays",
        "preview":"/static/main/catalog_files/images/relays/force-guided.png",
        "target":"_blank",
    }, 
    "rt1-inrush":{
        "category":"relays",
        "link":"/electrical/catalog/rt1-inrush",
        "filename":"rt1-inrush.pdf",
        "title":"Power PCB Relay RT1 Inrush",
        "preview":"/static/main/catalog_files/images/relays/rt1-inrush.png",
        "target":"_blank",
    }, 
    "spiral-ribbon":{
        "category":"spiral-ribbon",
        "link":"/electrical/catalog/spiral-ribbon",
        "filename":"spiral-ribbon.pdf",
        "title":"Спиральная лента",
        "preview":"/static/main/catalog_files/images/spiral-ribbon/spiral-ribbon.png",
        "target":"_blank",
    }, 
    "distribution-blocks":{
        "category":"distribution-blocks",
        "link":"/electrical/catalog/distribution-blocks",
        "filename":"distribution-blocks.pdf",
        "title":"Распределительные блоки серии DBL",
        "preview":"/static/main/catalog_files/images/distribution-blocks/distribution-blocks.png",
        "target":"_blank",
    }, 
    "industrial-rj45":{
        "category":"",
        "link":"/electrical/catalog/industrial-rj45",
        "filename":"industrial-rj45.pdf",
        "title":"Industrial RJ45 Jacks with Integrated Magnetics",
        "preview":"/static/main/catalog_files/images/industrial-rj45.png",
        "target":"_blank",
    }, 
    "plasti-grip-terminals":{
        "category":"",
        "link":"/electrical/catalog/plasti-grip-terminals",
        "filename":"plasti-grip-terminals.pdf",
        "title":"Plasti-Grip Terminals & Splices",
        "preview":"/static/main/catalog_files/images/plasti-grip-terminals.png",
        "target":"_blank",
    }, 
    "solistrand-terminals":{
        "category":"",
        "link":"/electrical/catalog/solistrand-terminals",
        "filename":"solistrand-terminals.pdf",
        "title":"Solistrand Terminals & Splices",
        "preview":"/static/main/catalog_files/images/solistrand-terminals.png",
        "target":"_blank",
    }, 
    "hv-contactors":{
        "category":"",
        "link":"/electrical/catalog/hv-contactors",
        "filename":"hv-contactors.pdf",
        "title":"High Voltage Contactors IHV50 Series",
        "preview":"/static/main/catalog_files/images/hv-contactors/hv-contactors.png",
        "target":"_blank",
    }, 
}