MODALS = {
    "modal-development-1":{ 
        "onclose":"/",
        "text":"Данная страница находится в разработке",
        "template":"electrical/modals/in_development.html"
    }, 
    "modal-0":{  
        "onclose":"javascript:CloseModal('modal-0')",
        "images":[
            "/static/main/images/modals/relays/panel-plugin/panel-plugin-0.png",
            "/static/main/images/modals/relays/panel-plugin/panel-plugin-1.png",
            "/static/main/images/modals/relays/panel-plugin/panel-plugin-2.png",
            "/static/main/images/modals/relays/panel-plugin/panel-plugin-3.png",
            "/static/main/images/modals/relays/panel-plugin/panel-plugin-4.png",
            "/static/main/images/modals/relays/panel-plugin/panel-plugin-5.png",
            "/static/main/images/modals/relays/panel-plugin/panel-plugin-6.png",
            "/static/main/images/modals/relays/panel-plugin/panel-plugin-7.png",
            "/static/main/images/modals/relays/panel-plugin/panel-plugin-8.png",
            "/static/main/images/modals/relays/panel-plugin/panel-plugin-9.png",
        ],  
        "template":"electrical/modals/image_modal.html",
    },
    "modal-1":{  
        "onclose":"javascript:CloseModal('modal-1')",
        "images":[ 
            "/static/main/images/modals/relays/solid-state/solid-state-0.png", 
            "/static/main/images/modals/relays/solid-state/solid-state-1.png", 
            "/static/main/images/modals/relays/solid-state/solid-state-2.png", 
        ],  
        "template":"electrical/modals/image_modal.html",
    },
    "modal-2":{  
        "onclose":"javascript:CloseModal('modal-2')",
        "images":[
            "/static/main/images/modals/relays/power-pcb/power-pcb-0.png", 
            "/static/main/images/modals/relays/power-pcb/power-pcb-1.png",
        ],  
        "template":"electrical/modals/image_modal.html",
    }, 
    "modal-3":{   
        "onclose":"javascript:CloseModal('modal-3')",
        "images":[],  
        "text":"Данный фрагмент находится в разработке",
        "template":"electrical/modals/in_development.html"
    },
    "modal-4":{  
        "onclose":"javascript:CloseModal('modal-4')",
        "images":[
            "/static/main/images/modals/relays/signal/signal-0.png", 
        ],  
        "template":"electrical/modals/image_modal.html",
    },
    "modal-5":{  
        "onclose":"javascript:CloseModal('modal-5')",
        "images":[
            "/static/main/images/modals/relays/inrush-power/inrush-power-0.png", 
        ],  
        "template":"electrical/modals/image_modal.html",
    },
    "modal-6":{ 
        "onclose":"javascript:CloseModal('modal-6')",
        "images":[
            "/static/main/images/modals/relays/force-guided/force-guided-0.png", 
            "/static/main/images/modals/relays/force-guided/force-guided-1.png", 
        ],  
        "template":"electrical/modals/image_modal.html",
    },
    "modal-7":{ 
        "onclose":"javascript:CloseModal('modal-7')", 
        "text":"Данный фрагмент находится в разработке",
        "template":"electrical/modals/in_development.html"
    },
}