MODALS = {
    "modal-development-1":{ 
        "onclose":"/electrical/",
        "text":"Данная страница находится в разработке",
        "template":"electrical/modals/in_development.html"
    },  
    "modal-0":{  
        "onclose":"javascript:CloseModal('modal-0')", 
        "blocks":{
            "0":{
                "image":"/static/main/images/modals/relays/panel-plugin/panel-plugin-0.png", 
            }, 
            "1":{
                "image":"/static/main/images/modals/relays/panel-plugin/panel-plugin-1.png", 
            }, 
            "2":{
                "image":"/static/main/images/modals/relays/panel-plugin/panel-plugin-2.png", 
            },  
            "3":{
                "image":"/static/main/images/modals/relays/panel-plugin/panel-plugin-3.png", 
            },  
            "4":{
                "image":"/static/main/images/modals/relays/panel-plugin/panel-plugin-4.png", 
            },  
            "5":{
                "image":"/static/main/images/modals/relays/panel-plugin/panel-plugin-5.png", 
            },  
            "6":{
                "image":"/static/main/images/modals/relays/panel-plugin/panel-plugin-6.png", 
            },  
            "7":{
                "image":"/static/main/images/modals/relays/panel-plugin/panel-plugin-7.png", 
            },  
            "8":{
                "image":"/static/main/images/modals/relays/panel-plugin/panel-plugin-8.png", 
            },  
            "9":{
                "image":"/static/main/images/modals/relays/panel-plugin/panel-plugin-9.png", 
            },  
        },  
        "template":"electrical/modals/image_modal.html",
    },
    "modal-1":{  
        "onclose":"javascript:CloseModal('modal-1')",
        "blocks":{
            "0":{
                "image":"/static/main/images/modals/relays/solid-state/solid-state-0.png", 
            }, 
            "1":{
                "image":"/static/main/images/modals/relays/solid-state/solid-state-1.png", 
            }, 
            "2":{
                "image":"/static/main/images/modals/relays/solid-state/solid-state-2.png", 
            },  
        },  
        "template":"electrical/modals/image_modal.html",
    },
    "modal-2":{  
        "onclose":"javascript:CloseModal('modal-2')", 
        "blocks":{
            "0":{
                "image":"/static/main/images/modals/relays/power-pcb/power-pcb-0.png", 
            }, 
            "1":{
                "image":"/static/main/images/modals/relays/power-pcb/power-pcb-1.png", 
            },  
        },  
        "template":"electrical/modals/image_modal.html",
    }, 
    "modal-3":{   
        "onclose":"javascript:CloseModal('modal-3')",
        "images":[],  
        "text":"Данный фрагмент находится в разработке",
        "template":"electrical/modals/in_development.html"
    },
    "modal-4":{  
        "onclose":"javascript:CloseModal('modal-4')", 
        "blocks":{
            "0":{
                "image":"/static/main/images/modals/relays/signal/signal-0.png", 
            },  
        },    
        "template":"electrical/modals/image_modal.html",
    },
    "modal-5":{  
        "onclose":"javascript:CloseModal('modal-5')", 
        "blocks":{
            "0":{
                "image":"/static/main/images/modals/relays/inrush-power/inrush-power-0.png", 
                "links":{
                    "Power PCB Relay RT1 Inrush":"/electrical/catalog/rt1-inrush",
                }
            },  
        },   
        "template":"electrical/modals/image_modal.html",
    },
    "modal-6":{ 
        "onclose":"javascript:CloseModal('modal-6')", 
        "blocks":{
            "0":{
                "image":"/static/main/images/modals/relays/force-guided/force-guided-0.png", 
            },  
            "1":{
                "image":"/static/main/images/modals/relays/force-guided/force-guided-1.png", 
            },
            "2":{
                "image":"/static/main/images/modals/relays/force-guided/force-guided-2.png", 
            },
        },  
        "template":"electrical/modals/image_modal.html",
    },
    "modal-7":{ 
        "onclose":"javascript:CloseModal('modal-7')", 
        "blocks":{
            "0":{
                "image":"/static/main/images/modals/relays/hv-contactors/hv-contactors-0.png", 
                "links":{
                    "Брошюра IHV50 Series":"/electrical/catalog/hv-contactors",
                },
            },  
            "1":{
                "image":"/static/main/images/modals/relays/hv-contactors/hv-contactors-1.png", 
                "links":{
                    "SCHRACK Force Guided Relays":"/electrical/catalog/force-guided",
                }, 
            }, 
        },   
        "template":"electrical/modals/image_modal.html",
    },
    "modal-8":{ 
        "onclose":"javascript:CloseModal('modal-8')", 
        "text":"Данный фрагмент находится в разработке",
        "template":"electrical/modals/in_development.html"
    },
}